version: "3.3"
services:
  kafka-producer-test:
    image: madajaju/kafka-producer-test
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: localhost:9094
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
