version: "3.3"
services:
  kafka-producer-test:
    image: madajaju/kafka-producer-test
    environment:
      HOSTNAME_COMMAND: host1
      KAFKA_ZOOKEEPER_CONNECT: host1:2181
      KAFKA_ADVERTISED_LISTENERS: host1:9094
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
